In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
             [3,4,5]])

In [7]:
len(a)

2

In [1]:
freqs = {('followfriday', 1.0): 23,
 ('top', 1.0): 30,
 ('engag', 1.0): 7,
 ('member', 1.0): 14,
 ('commun', 1.0): 27,
 ('week', 1.0): 72,
 (':)', 1.0): 2960,
 ('hey', 1.0): 60,
 ('jame', 1.0): 7,
 ('odd', 1.0): 2,
 (':/', 1.0): 5,
 ('pleas', 1.0): 81,
 ('call', 1.0): 27,
 ('contact', 1.0): 4,
 ('centr', 1.0): 1,
 ('02392441234', 1.0): 1,
 ('abl', 1.0): 6,
 ('assist', 1.0): 1,
 ('mani', 1.0): 28,
 ('thank', 1.0): 522,
 ('listen', 1.0): 15,
 ('last', 1.0): 39,
 ('night', 1.0): 55,
 ('bleed', 1.0): 2,
 ('amaz', 1.0): 41,
 ('track', 1.0): 5
}

In [24]:
vocab = [pair[0] for pair in freqs.keys()]
V = len(set(vocab))
V

26

In [36]:
for key in freqs.keys():
    word, _ = key
    print(_)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [3]:
import pandas as pd
df = pd.read_csv("https://github.com/hhtrieu0108/Ohitv_End_To_End_Project/raw/refs/heads/main/data/ohitv_film.csv")

In [12]:
x = np.array([[1,2,3],
              [4,5,6]])

In [16]:
a = np.cov(x)

In [18]:
eigh_val , eigh_vec  = np.linalg.eigh(a)

In [23]:
aa = eigh_vec.sort()

In [35]:
idx_sorted = np.argsort(eigh_val)

# reverse the order so that it's from highest to lowest.
idx_sorted_decreasing = idx_sorted[::-1]

# sort the eigen values by idx_sorted_decreasing
eigh_val_sorted = eigh_val[idx_sorted_decreasing]

# sort eigenvectors using the idx_sorted_decreasing indices
eigh_vec_sorted = eigh_vec[:, idx_sorted_decreasing]
eigh_vec_sorted_1 = eigh_vec[ idx_sorted_decreasing]

# select the first n eigenvectors (n is desired dimension
# of rescaled data array, or n_components)

eigh_vec_subset = eigh_vec_sorted[:, :2]

In [37]:
display(eigh_vec_sorted, eigh_vec_sorted_1)

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [1]:
import numpy as np

x = np.array([[1,1]])
P = np.array([[2,1]])

In [3]:
dot = np.dot(P, x.T)

In [6]:
sign = np.sign(dot)
sign

array([[1]])

In [16]:
sign_scalar = P[0][0].item()
sign_scalar


2